[package]
name = "mamastock"
version = "0.1.0"
edition = "2021"
description = "MamaStock"
authors = ["MamaStock"]
license = "MIT"

[dependencies]
tauri = { version = "2", features = ["wry"] }
tauri-plugin-sql = { version = "2.3", features = ["sqlite"] }
tauri-plugin-process = "2.3"
tauri-plugin-fs = "2.4"
tauri-plugin-dialog = "2.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[[bin]]
name = "mamastock"
path = "src/main.rs"
