[package]
name = "mamastock"
version = "0.1.0"
edition = "2021"
description = "MamaStock"
authors = ["MamaStock"]
license = "MIT"

[dependencies]
tauri = { version = "2", features = ["wry", "tray-icon"] }
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
tauri-plugin-process = "2"
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
log = "0.4"
tauri-plugin-log = { version = "2", features = ["colored"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-devtools = "2"


[build-dependencies]
tauri-build = { version = "2", features = [] }


[dependencies]
tauri-plugin-shell = "2"

