import type { Config } from "tailwindcss";

const config: Config = {
  content: ["index.html", "src/**/*.{ts,tsx,js,jsx}"],
  safelist: [
    "min-h-screen",
    "flex",
    "flex-1",
    "flex-col",
    "w-64",
    "md:w-72",
    "shrink-0",
    "border-r",
    "border-white/10",
    "bg-white/10",
    "bg-gradient-to-b",
    "from-zinc-900",
    "via-zinc-900/95",
    "to-zinc-950/90",
    "backdrop-blur-xl",
    "h-screen",
    "shadow-md",
    "text-white",
    "text-white/80",
    "text-white/60",
    "text-zinc-900",
    "text-zinc-600",
    "text-zinc-500",
    "text-mamastockGold",
    "text-xs",
    "text-sm",
    "text-lg",
    "font-semibold",
    "uppercase",
    "tracking-widest",
    "p-4",
    "p-6",
    "px-3",
    "py-0.5",
    "py-1.5",
    "mt-1",
    "mt-3",
    "mt-4",
    "mt-6",
    "mt-8",
    "mb-4",
    "ml-4",
    "mx-auto",
    "space-y-3",
    "space-y-4",
    "space-y-6",
    "gap-2",
    "gap-3",
    "gap-4",
    "inline-flex",
    "items-center",
    "items-start",
    "items-end",
    "items-baseline",
    "justify-center",
    "justify-between",
    "text-center",
    "text-shadow",
    "rounded-md",
    "rounded-full",
    "max-w-sm",
    "max-w-md",
    { pattern: /^md:(block|flex|inline-flex)$/ },
    { pattern: /^(hover:)?text-mamastockGold$/ },
    { pattern: /^(flex|items|justify)-(start|center|end|between)$/ },
    { pattern: /^gap-[1-6]$/ },
    { pattern: /^space-y-[1-6]$/ },
    { pattern: /^(bg|text|border)-(mamastockGold|white(?:\/10|\/20)?|zinc-(400|500|600|900))$/ }
  ],
  theme: {
    extend: {}
  },
  plugins: []
};

export default config;
