/* AUTO-GENERATED. Do not edit manually.
   * Generated by scripts/generate-navigation.cjs
   */
import React from "react";
import { NavLink } from "react-router-dom";

export default function SidebarAutogen() {
  return (
    <aside className="w-64 p-3 border-r border-border bg-background">
      <nav>
        <ul className="space-y-1">
        <li key="/consolidation/accessmultisites">
          <NavLink to="/consolidation/accessmultisites" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Access Multi Sites
          </NavLink>
        </li>
        <li key="/accueil">
          <NavLink to="/accueil" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Accueil
          </NavLink>
        </li>
        <li key="/achats/achatdetail">
          <NavLink to="/achats/achatdetail" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Achat Detail
          </NavLink>
        </li>
        <li key="/aide/aide">
          <NavLink to="/aide/aide" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Aide
          </NavLink>
        </li>
        <li key="/aidecontextuelle">
          <NavLink to="/aidecontextuelle" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Aide Contextuelle
          </NavLink>
        </li>
        <li key="/alertes">
          <NavLink to="/alertes" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Alertes
          </NavLink>
        </li>
        <li key="/taches/alertes">
          <NavLink to="/taches/alertes" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Alertes
          </NavLink>
        </li>
        <li key="/analyse/analyse">
          <NavLink to="/analyse/analyse" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Analyse
          </NavLink>
        </li>
        <li key="/analytique/analytiquedashboard">
          <NavLink to="/analytique/analytiquedashboard" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Analytique Dashboard
          </NavLink>
        </li>
        <li key="/fournisseurs/apifournisseurform">
          <NavLink to="/fournisseurs/apifournisseurform" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Api Fournisseur Form
          </NavLink>
        </li>
        <li key="/debug/auth">
          <NavLink to="/debug/auth" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Auth
          </NavLink>
        </li>
        <li key="/barmanager">
          <NavLink to="/barmanager" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Bar Manager
          </NavLink>
        </li>
        <li key="/bons_livraison/blcreate">
          <NavLink to="/bons_livraison/blcreate" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            BLCreate
          </NavLink>
        </li>
        <li key="/auth/blocked">
          <NavLink to="/auth/blocked" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Blocked
          </NavLink>
        </li>
        <li key="/carte/carte">
          <NavLink to="/carte/carte" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Carte
          </NavLink>
        </li>
        <li key="/carteplats">
          <NavLink to="/carteplats" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Carte Plats
          </NavLink>
        </li>
        <li key="/catalogue/cataloguesyncviewer">
          <NavLink to="/catalogue/cataloguesyncviewer" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Catalogue Sync Viewer
          </NavLink>
        </li>
        <li key="/legal/cgu">
          <NavLink to="/legal/cgu" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Cgu
          </NavLink>
        </li>
        <li key="/commandes/commandedetail">
          <NavLink to="/commandes/commandedetail" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Commande Detail
          </NavLink>
        </li>
        <li key="/supervision/comparateurfiches">
          <NavLink to="/supervision/comparateurfiches" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Comparateur Fiches
          </NavLink>
        </li>
        <li key="/consentements">
          <NavLink to="/consentements" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Consentements
          </NavLink>
        </li>
        <li key="/costboisson/costboisson">
          <NavLink to="/costboisson/costboisson" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Cost Boisson
          </NavLink>
        </li>
        <li key="/costing/costingcarte">
          <NavLink to="/costing/costingcarte" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Costing Carte
          </NavLink>
        </li>
        <li key="/dashboard">
          <NavLink to="/dashboard" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Dashboard
          </NavLink>
        </li>
        <li key="/documents/documentform">
          <NavLink to="/documents/documentform" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Document Form
          </NavLink>
        </li>
        <li key="/dossierdonnees">
          <NavLink to="/dossierdonnees" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Dossier Donnees
          </NavLink>
        </li>
        <li key="/parametrage/dossierdonnees">
          <NavLink to="/parametrage/dossierdonnees" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Dossier Donnees
          </NavLink>
        </li>
        <li key="/inventaire/ecartinventaire">
          <NavLink to="/inventaire/ecartinventaire" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Ecart Inventaire
          </NavLink>
        </li>
        <li key="/ecarts/ecarts">
          <NavLink to="/ecarts/ecarts" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Ecarts
          </NavLink>
        </li>
        <li key="/emails/emailsenvoyes">
          <NavLink to="/emails/emailsenvoyes" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Emails Envoyes
          </NavLink>
        </li>
        <li key="/engineeringmenu">
          <NavLink to="/engineeringmenu" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Engineering Menu
          </NavLink>
        </li>
        <li key="/factures/facturecreate">
          <NavLink to="/factures/facturecreate" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Facture Create
          </NavLink>
        </li>
        <li key="/parametres/familles">
          <NavLink to="/parametres/familles" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Familles
          </NavLink>
        </li>
        <li key="/feedback">
          <NavLink to="/feedback" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Feedback
          </NavLink>
        </li>
        <li key="/fiches/fichedetail">
          <NavLink to="/fiches/fichedetail" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Fiche Detail
          </NavLink>
        </li>
        <li key="/reporting/graphcost">
          <NavLink to="/reporting/graphcost" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Graph Cost
          </NavLink>
        </li>
        <li key="/helpcenter">
          <NavLink to="/helpcenter" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Help Center
          </NavLink>
        </li>
        <li key="/journal">
          <NavLink to="/journal" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Journal
          </NavLink>
        </li>
        <li key="/public/landingpage">
          <NavLink to="/public/landingpage" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Landing Page
          </NavLink>
        </li>
        <li key="/login">
          <NavLink to="/login" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Login
          </NavLink>
        </li>
        <li key="/menus/menudetail">
          <NavLink to="/menus/menudetail" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Menu Detail
          </NavLink>
        </li>
        <li key="/cuisine/menudujour">
          <NavLink to="/cuisine/menudujour" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Menu Du Jour
          </NavLink>
        </li>
        <li key="/menu/menudujour">
          <NavLink to="/menu/menudujour" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Menu Du Jour
          </NavLink>
        </li>
        <li key="/engineering/menuengineering">
          <NavLink to="/engineering/menuengineering" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Menu Engineering
          </NavLink>
        </li>
        <li key="/mobile/mobileaccueil">
          <NavLink to="/mobile/mobileaccueil" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Mobile Accueil
          </NavLink>
        </li>
        <li key="/notfound">
          <NavLink to="/notfound" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Not Found
          </NavLink>
        </li>
        <li key="/notifications/notificationsettingsform">
          <NavLink to="/notifications/notificationsettingsform" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Notification Settings Form
          </NavLink>
        </li>
        <li key="/onboarding">
          <NavLink to="/onboarding" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Onboarding
          </NavLink>
        </li>
        <li key="/pertes">
          <NavLink to="/pertes" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Pertes
          </NavLink>
        </li>
        <li key="/planning">
          <NavLink to="/planning" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Planning
          </NavLink>
        </li>
        <li key="/planningdetail">
          <NavLink to="/planningdetail" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Planning Detail
          </NavLink>
        </li>
        <li key="/planningform">
          <NavLink to="/planningform" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Planning Form
          </NavLink>
        </li>
        <li key="/planningmodule">
          <NavLink to="/planningmodule" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Planning Module
          </NavLink>
        </li>
        <li key="/produits/produitdetail">
          <NavLink to="/produits/produitdetail" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Produit Detail
          </NavLink>
        </li>
        <li key="/promotions/promotionform">
          <NavLink to="/promotions/promotionform" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Promotion Form
          </NavLink>
        </li>
        <li key="/receptions/receptions">
          <NavLink to="/receptions/receptions" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Receptions
          </NavLink>
        </li>
        <li key="/recettes/recettes">
          <NavLink to="/recettes/recettes" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Recettes
          </NavLink>
        </li>
        <li key="/requisitions/requisitiondetail">
          <NavLink to="/requisitions/requisitiondetail" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Requisition Detail
          </NavLink>
        </li>
        <li key="/rgpd">
          <NavLink to="/rgpd" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Rgpd
          </NavLink>
        </li>
        <li key="/signalements/signalementdetail">
          <NavLink to="/signalements/signalementdetail" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Signalement Detail
          </NavLink>
        </li>
        <li key="/simulation/simulation">
          <NavLink to="/simulation/simulation" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Simulation
          </NavLink>
        </li>
        <li key="/stats/stats">
          <NavLink to="/stats/stats" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Stats
          </NavLink>
        </li>
        <li key="/stock">
          <NavLink to="/stock" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Stock
          </NavLink>
        </li>
        <li key="/surcouts/surcouts">
          <NavLink to="/surcouts/surcouts" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Surcouts
          </NavLink>
        </li>
        <li key="/utilisateurs">
          <NavLink to="/utilisateurs" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Utilisateurs
          </NavLink>
        </li>
        <li key="/validations">
          <NavLink to="/validations" className={({isActive}) => "block px-3 py-2 rounded hover:bg-muted " + (isActive ? "font-semibold" : "")}>
            Validations
          </NavLink>
        </li>
        </ul>
      </nav>
    </aside>
  );
}
