/* AUTO-GENERATED. Do not edit manually.
   * Generated by scripts/generate-navigation.cjs
   */
import React, { lazy } from "react";
import { registerRoutePrefetch } from "@/routerPrefetch";

const import_Page_0 = () => import(/* webpackChunkName: "page-pages-accueil" */ "@/pages/Accueil");
registerRoutePrefetch("/accueil", import_Page_0);
const Page_0 = lazy(import_Page_0);
const import_Page_1 = () => import(/* webpackChunkName: "page-pages-achats-achatdetail" */ "@/pages/achats/AchatDetail");
registerRoutePrefetch("/achats/achatdetail", import_Page_1);
const Page_1 = lazy(import_Page_1);
const import_Page_2 = () => import(/* webpackChunkName: "page-pages-achats-achatform" */ "@/pages/achats/AchatForm");
registerRoutePrefetch("/achats/achatform", import_Page_2);
const Page_2 = lazy(import_Page_2);
const import_Page_3 = () => import(/* webpackChunkName: "page-pages-achats-achats" */ "@/pages/achats/Achats");
registerRoutePrefetch("/achats/achats", import_Page_3);
const Page_3 = lazy(import_Page_3);
const import_Page_4 = () => import(/* webpackChunkName: "page-pages-alertes" */ "@/pages/Alertes");
registerRoutePrefetch("/alertes", import_Page_4);
const Page_4 = lazy(import_Page_4);
const import_Page_5 = () => import(/* webpackChunkName: "page-pages-analyse-analyse" */ "@/pages/analyse/Analyse");
registerRoutePrefetch("/analyse/analyse", import_Page_5);
const Page_5 = lazy(import_Page_5);
const import_Page_6 = () => import(/* webpackChunkName: "page-pages-analyse-analysecostcenter" */ "@/pages/analyse/AnalyseCostCenter");
registerRoutePrefetch("/analyse/analysecostcenter", import_Page_6);
const Page_6 = lazy(import_Page_6);
const import_Page_7 = () => import(/* webpackChunkName: "page-pages-analyse-menuengineering" */ "@/pages/analyse/MenuEngineering");
registerRoutePrefetch("/analyse/menuengineering", import_Page_7);
const Page_7 = lazy(import_Page_7);
const import_Page_8 = () => import(/* webpackChunkName: "page-pages-analyse-tableauxdebord" */ "@/pages/analyse/TableauxDeBord");
registerRoutePrefetch("/analyse/tableauxdebord", import_Page_8);
const Page_8 = lazy(import_Page_8);
const import_Page_9 = () => import(/* webpackChunkName: "page-pages-analytique-analytiquedashboard" */ "@/pages/analytique/AnalytiqueDashboard");
registerRoutePrefetch("/analytique/analytiquedashboard", import_Page_9);
const Page_9 = lazy(import_Page_9);
const import_Page_10 = () => import(/* webpackChunkName: "page-pages-auth-blocked" */ "@/pages/auth/Blocked");
registerRoutePrefetch("/auth/blocked", import_Page_10);
const Page_10 = lazy(import_Page_10);
const import_Page_11 = () => import(/* webpackChunkName: "page-pages-auth-createmama" */ "@/pages/auth/CreateMama");
registerRoutePrefetch("/auth/createmama", import_Page_11);
const Page_11 = lazy(import_Page_11);
const import_Page_12 = () => import(/* webpackChunkName: "page-pages-auth-logout" */ "@/pages/auth/Logout");
registerRoutePrefetch("/auth/logout", import_Page_12);
const Page_12 = lazy(import_Page_12);
const import_Page_13 = () => import(/* webpackChunkName: "page-pages-auth-pending" */ "@/pages/auth/Pending");
registerRoutePrefetch("/auth/pending", import_Page_13);
const Page_13 = lazy(import_Page_13);
const import_Page_14 = () => import(/* webpackChunkName: "page-pages-auth-resetpassword" */ "@/pages/auth/ResetPassword");
registerRoutePrefetch("/auth/resetpassword", import_Page_14);
const Page_14 = lazy(import_Page_14);
const import_Page_15 = () => import(/* webpackChunkName: "page-pages-auth-roleerror" */ "@/pages/auth/RoleError");
registerRoutePrefetch("/auth/roleerror", import_Page_15);
const Page_15 = lazy(import_Page_15);
const import_Page_16 = () => import(/* webpackChunkName: "page-pages-auth-unauthorized" */ "@/pages/auth/Unauthorized");
registerRoutePrefetch("/auth/unauthorized", import_Page_16);
const Page_16 = lazy(import_Page_16);
const import_Page_17 = () => import(/* webpackChunkName: "page-pages-auth-updatepassword" */ "@/pages/auth/UpdatePassword");
registerRoutePrefetch("/auth/updatepassword", import_Page_17);
const Page_17 = lazy(import_Page_17);
const import_Page_18 = () => import(/* webpackChunkName: "page-pages-barmanager" */ "@/pages/BarManager");
registerRoutePrefetch("/barmanager", import_Page_18);
const Page_18 = lazy(import_Page_18);
const import_Page_19 = () => import(/* webpackChunkName: "page-pages-bons-livraison-blcreate" */ "@/pages/bons_livraison/BLCreate");
registerRoutePrefetch("/bons_livraison/blcreate", import_Page_19);
const Page_19 = lazy(import_Page_19);
const import_Page_20 = () => import(/* webpackChunkName: "page-pages-bons-livraison-bldetail" */ "@/pages/bons_livraison/BLDetail");
registerRoutePrefetch("/bons_livraison/bldetail", import_Page_20);
const Page_20 = lazy(import_Page_20);
const import_Page_21 = () => import(/* webpackChunkName: "page-pages-bons-livraison-blform" */ "@/pages/bons_livraison/BLForm");
registerRoutePrefetch("/bons_livraison/blform", import_Page_21);
const Page_21 = lazy(import_Page_21);
const import_Page_22 = () => import(/* webpackChunkName: "page-pages-bons-livraison-bonslivraison" */ "@/pages/bons_livraison/BonsLivraison");
registerRoutePrefetch("/bons_livraison/bonslivraison", import_Page_22);
const Page_22 = lazy(import_Page_22);
const import_Page_23 = () => import(/* webpackChunkName: "page-pages-carte-carte" */ "@/pages/carte/Carte");
registerRoutePrefetch("/carte/carte", import_Page_23);
const Page_23 = lazy(import_Page_23);
const import_Page_24 = () => import(/* webpackChunkName: "page-pages-carteplats" */ "@/pages/CartePlats");
registerRoutePrefetch("/carteplats", import_Page_24);
const Page_24 = lazy(import_Page_24);
const import_Page_25 = () => import(/* webpackChunkName: "page-pages-catalogue-cataloguesyncviewer" */ "@/pages/catalogue/CatalogueSyncViewer");
registerRoutePrefetch("/catalogue/cataloguesyncviewer", import_Page_25);
const Page_25 = lazy(import_Page_25);
const import_Page_26 = () => import(/* webpackChunkName: "page-pages-commandes-commandedetail" */ "@/pages/commandes/CommandeDetail");
registerRoutePrefetch("/commandes/commandedetail", import_Page_26);
const Page_26 = lazy(import_Page_26);
const import_Page_27 = () => import(/* webpackChunkName: "page-pages-commandes-commandeform" */ "@/pages/commandes/CommandeForm");
registerRoutePrefetch("/commandes/commandeform", import_Page_27);
const Page_27 = lazy(import_Page_27);
const import_Page_28 = () => import(/* webpackChunkName: "page-pages-commandes-commandes" */ "@/pages/commandes/Commandes");
registerRoutePrefetch("/commandes/commandes", import_Page_28);
const Page_28 = lazy(import_Page_28);
const import_Page_29 = () => import(/* webpackChunkName: "page-pages-commandes-commandesenvoyees" */ "@/pages/commandes/CommandesEnvoyees");
registerRoutePrefetch("/commandes/commandesenvoyees", import_Page_29);
const Page_29 = lazy(import_Page_29);
const import_Page_30 = () => import(/* webpackChunkName: "page-pages-consentements" */ "@/pages/Consentements");
registerRoutePrefetch("/consentements", import_Page_30);
const Page_30 = lazy(import_Page_30);
const import_Page_31 = () => import(/* webpackChunkName: "page-pages-consolidation-accessmultisites" */ "@/pages/consolidation/AccessMultiSites");
registerRoutePrefetch("/consolidation/accessmultisites", import_Page_31);
const Page_31 = lazy(import_Page_31);
const import_Page_32 = () => import(/* webpackChunkName: "page-pages-consolidation-consolidation" */ "@/pages/consolidation/Consolidation");
registerRoutePrefetch("/consolidation/consolidation", import_Page_32);
const Page_32 = lazy(import_Page_32);
const import_Page_33 = () => import(/* webpackChunkName: "page-pages-costboisson-costboisson" */ "@/pages/costboisson/CostBoisson");
registerRoutePrefetch("/costboisson/costboisson", import_Page_33);
const Page_33 = lazy(import_Page_33);
const import_Page_34 = () => import(/* webpackChunkName: "page-pages-costing-costingcarte" */ "@/pages/costing/CostingCarte");
registerRoutePrefetch("/costing/costingcarte", import_Page_34);
const Page_34 = lazy(import_Page_34);
const import_Page_35 = () => import(/* webpackChunkName: "page-pages-cuisine-menudujour" */ "@/pages/cuisine/MenuDuJour");
registerRoutePrefetch("/cuisine/menudujour", import_Page_35);
const Page_35 = lazy(import_Page_35);
const import_Page_36 = () => import(/* webpackChunkName: "page-pages-dashboard" */ "@/pages/Dashboard");
registerRoutePrefetch("/dashboard", import_Page_36);
const Page_36 = lazy(import_Page_36);
const import_Page_37 = () => import(/* webpackChunkName: "page-pages-dashboard-dashboardbuilder" */ "@/pages/dashboard/DashboardBuilder");
registerRoutePrefetch("/dashboard/dashboardbuilder", import_Page_37);
const Page_37 = lazy(import_Page_37);
const import_Page_38 = () => import(/* webpackChunkName: "page-pages-dbsetup" */ "@/pages/DbSetup");
registerRoutePrefetch("/dbsetup", import_Page_38);
const Page_38 = lazy(import_Page_38);
const import_Page_39 = () => import(/* webpackChunkName: "page-pages-debug-accessexample" */ "@/pages/debug/AccessExample");
registerRoutePrefetch("/debug/accessexample", import_Page_39);
const Page_39 = lazy(import_Page_39);
const import_Page_40 = () => import(/* webpackChunkName: "page-pages-debug-auth" */ "@/pages/Debug/Auth");
registerRoutePrefetch("/debug/auth", import_Page_40);
const Page_40 = lazy(import_Page_40);
const import_Page_41 = () => import(/* webpackChunkName: "page-pages-debug-auth" */ "@/pages/debug/Auth");
registerRoutePrefetch("/debug/auth", import_Page_41);
const Page_41 = lazy(import_Page_41);
const import_Page_42 = () => import(/* webpackChunkName: "page-pages-debug-authdebug" */ "@/pages/debug/AuthDebug");
registerRoutePrefetch("/debug/authdebug", import_Page_42);
const Page_42 = lazy(import_Page_42);
const import_Page_43 = () => import(/* webpackChunkName: "page-pages-debug-debug" */ "@/pages/debug/Debug");
registerRoutePrefetch("/debug/debug", import_Page_43);
const Page_43 = lazy(import_Page_43);
const import_Page_44 = () => import(/* webpackChunkName: "page-pages-debug-debugauth" */ "@/pages/debug/DebugAuth");
registerRoutePrefetch("/debug/debugauth", import_Page_44);
const Page_44 = lazy(import_Page_44);
const import_Page_45 = () => import(/* webpackChunkName: "page-pages-debug-debugrights" */ "@/pages/debug/DebugRights");
registerRoutePrefetch("/debug/debugrights", import_Page_45);
const Page_45 = lazy(import_Page_45);
const import_Page_46 = () => import(/* webpackChunkName: "page-pages-debug-debuguser" */ "@/pages/debug/DebugUser");
registerRoutePrefetch("/debug/debuguser", import_Page_46);
const Page_46 = lazy(import_Page_46);
const import_Page_47 = () => import(/* webpackChunkName: "page-pages-documents-documentform" */ "@/pages/documents/DocumentForm");
registerRoutePrefetch("/documents/documentform", import_Page_47);
const Page_47 = lazy(import_Page_47);
const import_Page_48 = () => import(/* webpackChunkName: "page-pages-documents-documents" */ "@/pages/documents/Documents");
registerRoutePrefetch("/documents/documents", import_Page_48);
const Page_48 = lazy(import_Page_48);
const import_Page_49 = () => import(/* webpackChunkName: "page-pages-dossierdonnees" */ "@/pages/DossierDonnees");
registerRoutePrefetch("/dossierdonnees", import_Page_49);
const Page_49 = lazy(import_Page_49);
const import_Page_50 = () => import(/* webpackChunkName: "page-pages-ecarts-ecarts" */ "@/pages/ecarts/Ecarts");
registerRoutePrefetch("/ecarts/ecarts", import_Page_50);
const Page_50 = lazy(import_Page_50);
const import_Page_51 = () => import(/* webpackChunkName: "page-pages-emails-emailsenvoyes" */ "@/pages/emails/EmailsEnvoyes");
registerRoutePrefetch("/emails/emailsenvoyes", import_Page_51);
const Page_51 = lazy(import_Page_51);
const import_Page_52 = () => import(/* webpackChunkName: "page-pages-engineering-menuengineering" */ "@/pages/engineering/MenuEngineering");
registerRoutePrefetch("/engineering/menuengineering", import_Page_52);
const Page_52 = lazy(import_Page_52);
const import_Page_53 = () => import(/* webpackChunkName: "page-pages-engineeringmenu" */ "@/pages/EngineeringMenu");
registerRoutePrefetch("/engineeringmenu", import_Page_53);
const Page_53 = lazy(import_Page_53);
const import_Page_54 = () => import(/* webpackChunkName: "page-pages-factures-facturecreate" */ "@/pages/factures/FactureCreate");
registerRoutePrefetch("/factures/facturecreate", import_Page_54);
const Page_54 = lazy(import_Page_54);
const import_Page_55 = () => import(/* webpackChunkName: "page-pages-factures-facturedetail" */ "@/pages/factures/FactureDetail");
registerRoutePrefetch("/factures/facturedetail", import_Page_55);
const Page_55 = lazy(import_Page_55);
const import_Page_56 = () => import(/* webpackChunkName: "page-pages-factures-factureform" */ "@/pages/factures/FactureForm");
registerRoutePrefetch("/factures/factureform", import_Page_56);
const Page_56 = lazy(import_Page_56);
const import_Page_57 = () => import(/* webpackChunkName: "page-pages-factures-factures" */ "@/pages/factures/Factures");
registerRoutePrefetch("/factures/factures", import_Page_57);
const Page_57 = lazy(import_Page_57);
const import_Page_58 = () => import(/* webpackChunkName: "page-pages-factures-importfactures" */ "@/pages/factures/ImportFactures");
registerRoutePrefetch("/factures/importfactures", import_Page_58);
const Page_58 = lazy(import_Page_58);
const import_Page_59 = () => import(/* webpackChunkName: "page-pages-feedback" */ "@/pages/Feedback");
registerRoutePrefetch("/feedback", import_Page_59);
const Page_59 = lazy(import_Page_59);
const import_Page_60 = () => import(/* webpackChunkName: "page-pages-fiches-fichedetail" */ "@/pages/fiches/FicheDetail");
registerRoutePrefetch("/fiches/fichedetail", import_Page_60);
const Page_60 = lazy(import_Page_60);
const import_Page_61 = () => import(/* webpackChunkName: "page-pages-fiches-ficheform" */ "@/pages/fiches/FicheForm");
registerRoutePrefetch("/fiches/ficheform", import_Page_61);
const Page_61 = lazy(import_Page_61);
const import_Page_62 = () => import(/* webpackChunkName: "page-pages-fiches-fiches" */ "@/pages/fiches/Fiches");
registerRoutePrefetch("/fiches/fiches", import_Page_62);
const Page_62 = lazy(import_Page_62);
const import_Page_63 = () => import(/* webpackChunkName: "page-pages-fournisseurs-apifournisseurform" */ "@/pages/fournisseurs/ApiFournisseurForm");
registerRoutePrefetch("/fournisseurs/apifournisseurform", import_Page_63);
const Page_63 = lazy(import_Page_63);
const import_Page_64 = () => import(/* webpackChunkName: "page-pages-fournisseurs-apifournisseurs" */ "@/pages/fournisseurs/ApiFournisseurs");
registerRoutePrefetch("/fournisseurs/apifournisseurs", import_Page_64);
const Page_64 = lazy(import_Page_64);
const import_Page_65 = () => import(/* webpackChunkName: "page-pages-fournisseurs-comparatif-comparatifprix" */ "@/pages/fournisseurs/comparatif/ComparatifPrix");
registerRoutePrefetch("/fournisseurs/comparatif/comparatifprix", import_Page_65);
const Page_65 = lazy(import_Page_65);
const import_Page_66 = () => import(/* webpackChunkName: "page-pages-fournisseurs-comparatif-prixfournisseurs" */ "@/pages/fournisseurs/comparatif/PrixFournisseurs");
registerRoutePrefetch("/fournisseurs/comparatif/prixfournisseurs", import_Page_66);
const Page_66 = lazy(import_Page_66);
const import_Page_67 = () => import(/* webpackChunkName: "page-pages-fournisseurs-fournisseurapisettingsform" */ "@/pages/fournisseurs/FournisseurApiSettingsForm");
registerRoutePrefetch("/fournisseurs/fournisseurapisettingsform", import_Page_67);
const Page_67 = lazy(import_Page_67);
const import_Page_68 = () => import(/* webpackChunkName: "page-pages-fournisseurs-fournisseurcreate" */ "@/pages/fournisseurs/FournisseurCreate");
registerRoutePrefetch("/fournisseurs/fournisseurcreate", import_Page_68);
const Page_68 = lazy(import_Page_68);
const import_Page_69 = () => import(/* webpackChunkName: "page-pages-fournisseurs-fournisseurdetail" */ "@/pages/fournisseurs/FournisseurDetail");
registerRoutePrefetch("/fournisseurs/fournisseurdetail", import_Page_69);
const Page_69 = lazy(import_Page_69);
const import_Page_70 = () => import(/* webpackChunkName: "page-pages-fournisseurs-fournisseurdetailpage" */ "@/pages/fournisseurs/FournisseurDetailPage");
registerRoutePrefetch("/fournisseurs/fournisseurdetailpage", import_Page_70);
const Page_70 = lazy(import_Page_70);
const import_Page_71 = () => import(/* webpackChunkName: "page-pages-fournisseurs-fournisseurform" */ "@/pages/fournisseurs/FournisseurForm");
registerRoutePrefetch("/fournisseurs/fournisseurform", import_Page_71);
const Page_71 = lazy(import_Page_71);
const import_Page_72 = () => import(/* webpackChunkName: "page-pages-fournisseurs-fournisseurs" */ "@/pages/fournisseurs/Fournisseurs");
registerRoutePrefetch("/fournisseurs/fournisseurs", import_Page_72);
const Page_72 = lazy(import_Page_72);
const import_Page_73 = () => import(/* webpackChunkName: "page-pages-inventaire-ecartinventaire" */ "@/pages/inventaire/EcartInventaire");
registerRoutePrefetch("/inventaire/ecartinventaire", import_Page_73);
const Page_73 = lazy(import_Page_73);
const import_Page_74 = () => import(/* webpackChunkName: "page-pages-inventaire-inventaire" */ "@/pages/inventaire/Inventaire");
registerRoutePrefetch("/inventaire/inventaire", import_Page_74);
const Page_74 = lazy(import_Page_74);
const import_Page_75 = () => import(/* webpackChunkName: "page-pages-inventaire-inventairedetail" */ "@/pages/inventaire/InventaireDetail");
registerRoutePrefetch("/inventaire/inventairedetail", import_Page_75);
const Page_75 = lazy(import_Page_75);
const import_Page_76 = () => import(/* webpackChunkName: "page-pages-inventaire-inventaireform" */ "@/pages/inventaire/InventaireForm");
registerRoutePrefetch("/inventaire/inventaireform", import_Page_76);
const Page_76 = lazy(import_Page_76);
const import_Page_77 = () => import(/* webpackChunkName: "page-pages-inventaire-inventairezones" */ "@/pages/inventaire/InventaireZones");
registerRoutePrefetch("/inventaire/inventairezones", import_Page_77);
const Page_77 = lazy(import_Page_77);
const import_Page_78 = () => import(/* webpackChunkName: "page-pages-journal" */ "@/pages/Journal");
registerRoutePrefetch("/journal", import_Page_78);
const Page_78 = lazy(import_Page_78);
const import_Page_79 = () => import(/* webpackChunkName: "page-pages-legal-cgu" */ "@/pages/legal/Cgu");
registerRoutePrefetch("/legal/cgu", import_Page_79);
const Page_79 = lazy(import_Page_79);
const import_Page_80 = () => import(/* webpackChunkName: "page-pages-legal-cgv" */ "@/pages/legal/Cgv");
registerRoutePrefetch("/legal/cgv", import_Page_80);
const Page_80 = lazy(import_Page_80);
const import_Page_81 = () => import(/* webpackChunkName: "page-pages-legal-confidentialite" */ "@/pages/legal/Confidentialite");
registerRoutePrefetch("/legal/confidentialite", import_Page_81);
const Page_81 = lazy(import_Page_81);
const import_Page_82 = () => import(/* webpackChunkName: "page-pages-legal-contact" */ "@/pages/legal/Contact");
registerRoutePrefetch("/legal/contact", import_Page_82);
const Page_82 = lazy(import_Page_82);
const import_Page_83 = () => import(/* webpackChunkName: "page-pages-legal-licence" */ "@/pages/legal/Licence");
registerRoutePrefetch("/legal/licence", import_Page_83);
const Page_83 = lazy(import_Page_83);
const import_Page_84 = () => import(/* webpackChunkName: "page-pages-legal-mentionslegales" */ "@/pages/legal/MentionsLegales");
registerRoutePrefetch("/legal/mentionslegales", import_Page_84);
const Page_84 = lazy(import_Page_84);
const import_Page_85 = () => import(/* webpackChunkName: "page-pages-login" */ "@/pages/Login");
registerRoutePrefetch("/login", import_Page_85);
const Page_85 = lazy(import_Page_85);
const import_Page_86 = () => import(/* webpackChunkName: "page-pages-menu-menudujour" */ "@/pages/menu/MenuDuJour");
registerRoutePrefetch("/menu/menudujour", import_Page_86);
const Page_86 = lazy(import_Page_86);
const import_Page_87 = () => import(/* webpackChunkName: "page-pages-menu-menudujourjour" */ "@/pages/menu/MenuDuJourJour");
registerRoutePrefetch("/menu/menudujourjour", import_Page_87);
const Page_87 = lazy(import_Page_87);
const import_Page_88 = () => import(/* webpackChunkName: "page-pages-menus-menudetail" */ "@/pages/menus/MenuDetail");
registerRoutePrefetch("/menus/menudetail", import_Page_88);
const Page_88 = lazy(import_Page_88);
const import_Page_89 = () => import(/* webpackChunkName: "page-pages-menus-menudujour" */ "@/pages/menus/MenuDuJour");
registerRoutePrefetch("/menus/menudujour", import_Page_89);
const Page_89 = lazy(import_Page_89);
const import_Page_90 = () => import(/* webpackChunkName: "page-pages-menus-menudujourdetail" */ "@/pages/menus/MenuDuJourDetail");
registerRoutePrefetch("/menus/menudujourdetail", import_Page_90);
const Page_90 = lazy(import_Page_90);
const import_Page_91 = () => import(/* webpackChunkName: "page-pages-menus-menudujourform" */ "@/pages/menus/MenuDuJourForm");
registerRoutePrefetch("/menus/menudujourform", import_Page_91);
const Page_91 = lazy(import_Page_91);
const import_Page_92 = () => import(/* webpackChunkName: "page-pages-menus-menuform" */ "@/pages/menus/MenuForm");
registerRoutePrefetch("/menus/menuform", import_Page_92);
const Page_92 = lazy(import_Page_92);
const import_Page_93 = () => import(/* webpackChunkName: "page-pages-menus-menugroupedetail" */ "@/pages/menus/MenuGroupeDetail");
registerRoutePrefetch("/menus/menugroupedetail", import_Page_93);
const Page_93 = lazy(import_Page_93);
const import_Page_94 = () => import(/* webpackChunkName: "page-pages-menus-menugroupeform" */ "@/pages/menus/MenuGroupeForm");
registerRoutePrefetch("/menus/menugroupeform", import_Page_94);
const Page_94 = lazy(import_Page_94);
const import_Page_95 = () => import(/* webpackChunkName: "page-pages-menus-menugroupes" */ "@/pages/menus/MenuGroupes");
registerRoutePrefetch("/menus/menugroupes", import_Page_95);
const Page_95 = lazy(import_Page_95);
const import_Page_96 = () => import(/* webpackChunkName: "page-pages-menus-menupdf" */ "@/pages/menus/MenuPDF");
registerRoutePrefetch("/menus/menupdf", import_Page_96);
const Page_96 = lazy(import_Page_96);
const import_Page_97 = () => import(/* webpackChunkName: "page-pages-menus-menus" */ "@/pages/menus/Menus");
registerRoutePrefetch("/menus/menus", import_Page_97);
const Page_97 = lazy(import_Page_97);
const import_Page_98 = () => import(/* webpackChunkName: "page-pages-mobile-mobileaccueil" */ "@/pages/mobile/MobileAccueil");
registerRoutePrefetch("/mobile/mobileaccueil", import_Page_98);
const Page_98 = lazy(import_Page_98);
const import_Page_99 = () => import(/* webpackChunkName: "page-pages-mobile-mobileinventaire" */ "@/pages/mobile/MobileInventaire");
registerRoutePrefetch("/mobile/mobileinventaire", import_Page_99);
const Page_99 = lazy(import_Page_99);
const import_Page_100 = () => import(/* webpackChunkName: "page-pages-mobile-mobilerequisition" */ "@/pages/mobile/MobileRequisition");
registerRoutePrefetch("/mobile/mobilerequisition", import_Page_100);
const Page_100 = lazy(import_Page_100);
const import_Page_101 = () => import(/* webpackChunkName: "page-pages-notfound" */ "@/pages/NotFound");
registerRoutePrefetch("/notfound", import_Page_101);
const Page_101 = lazy(import_Page_101);
const import_Page_102 = () => import(/* webpackChunkName: "page-pages-notifications-notificationsettingsform" */ "@/pages/notifications/NotificationSettingsForm");
registerRoutePrefetch("/notifications/notificationsettingsform", import_Page_102);
const Page_102 = lazy(import_Page_102);
const import_Page_103 = () => import(/* webpackChunkName: "page-pages-notifications-notificationsinbox" */ "@/pages/notifications/NotificationsInbox");
registerRoutePrefetch("/notifications/notificationsinbox", import_Page_103);
const Page_103 = lazy(import_Page_103);
const import_Page_104 = () => import(/* webpackChunkName: "page-pages-parametrage-accessrights" */ "@/pages/parametrage/AccessRights");
registerRoutePrefetch("/parametrage/accessrights", import_Page_104);
const Page_104 = lazy(import_Page_104);
const import_Page_105 = () => import(/* webpackChunkName: "page-pages-parametrage-apikeys" */ "@/pages/parametrage/APIKeys");
registerRoutePrefetch("/parametrage/apikeys", import_Page_105);
const Page_105 = lazy(import_Page_105);
const import_Page_106 = () => import(/* webpackChunkName: "page-pages-parametrage-centrecoutform" */ "@/pages/parametrage/CentreCoutForm");
registerRoutePrefetch("/parametrage/centrecoutform", import_Page_106);
const Page_106 = lazy(import_Page_106);
const import_Page_107 = () => import(/* webpackChunkName: "page-pages-parametrage-compteslocaux" */ "@/pages/parametrage/ComptesLocaux");
registerRoutePrefetch("/parametrage/compteslocaux", import_Page_107);
const Page_107 = lazy(import_Page_107);
const import_Page_108 = () => import(/* webpackChunkName: "page-pages-parametrage-dossierdonnees" */ "@/pages/Parametrage/DossierDonnees");
registerRoutePrefetch("/parametrage/dossierdonnees", import_Page_108);
const Page_108 = lazy(import_Page_108);
const import_Page_109 = () => import(/* webpackChunkName: "page-pages-parametrage-dossierdonnees" */ "@/pages/parametrage/DossierDonnees");
registerRoutePrefetch("/parametrage/dossierdonnees", import_Page_109);
const Page_109 = lazy(import_Page_109);
const import_Page_110 = () => import(/* webpackChunkName: "page-pages-parametrage-exportcomptapage" */ "@/pages/parametrage/ExportComptaPage");
registerRoutePrefetch("/parametrage/exportcomptapage", import_Page_110);
const Page_110 = lazy(import_Page_110);
const import_Page_111 = () => import(/* webpackChunkName: "page-pages-parametrage-exportuserdata" */ "@/pages/parametrage/ExportUserData");
registerRoutePrefetch("/parametrage/exportuserdata", import_Page_111);
const Page_111 = lazy(import_Page_111);
const import_Page_112 = () => import(/* webpackChunkName: "page-pages-parametrage-familles" */ "@/pages/Parametrage/Familles");
registerRoutePrefetch("/parametrage/familles", import_Page_112);
const Page_112 = lazy(import_Page_112);
const import_Page_113 = () => import(/* webpackChunkName: "page-pages-parametrage-familles" */ "@/pages/parametrage/Familles");
registerRoutePrefetch("/parametrage/familles", import_Page_113);
const Page_113 = lazy(import_Page_113);
const import_Page_114 = () => import(/* webpackChunkName: "page-pages-parametrage-invitationsenattente" */ "@/pages/parametrage/InvitationsEnAttente");
registerRoutePrefetch("/parametrage/invitationsenattente", import_Page_114);
const Page_114 = lazy(import_Page_114);
const import_Page_115 = () => import(/* webpackChunkName: "page-pages-parametrage-inviteuser" */ "@/pages/parametrage/InviteUser");
registerRoutePrefetch("/parametrage/inviteuser", import_Page_115);
const Page_115 = lazy(import_Page_115);
const import_Page_116 = () => import(/* webpackChunkName: "page-pages-parametrage-mamaform" */ "@/pages/parametrage/MamaForm");
registerRoutePrefetch("/parametrage/mamaform", import_Page_116);
const Page_116 = lazy(import_Page_116);
const import_Page_117 = () => import(/* webpackChunkName: "page-pages-parametrage-mamas" */ "@/pages/parametrage/Mamas");
registerRoutePrefetch("/parametrage/mamas", import_Page_117);
const Page_117 = lazy(import_Page_117);
const import_Page_118 = () => import(/* webpackChunkName: "page-pages-parametrage-mamasettingsform" */ "@/pages/parametrage/MamaSettingsForm");
registerRoutePrefetch("/parametrage/mamasettingsform", import_Page_118);
const Page_118 = lazy(import_Page_118);
const import_Page_119 = () => import(/* webpackChunkName: "page-pages-parametrage-parametrage" */ "@/pages/parametrage/Parametrage");
registerRoutePrefetch("/parametrage/parametrage", import_Page_119);
const Page_119 = lazy(import_Page_119);
const import_Page_120 = () => import(/* webpackChunkName: "page-pages-parametrage-parametrescommandes" */ "@/pages/parametrage/ParametresCommandes");
registerRoutePrefetch("/parametrage/parametrescommandes", import_Page_120);
const Page_120 = lazy(import_Page_120);
const import_Page_121 = () => import(/* webpackChunkName: "page-pages-parametrage-periodes" */ "@/pages/parametrage/Periodes");
registerRoutePrefetch("/parametrage/periodes", import_Page_121);
const Page_121 = lazy(import_Page_121);
const import_Page_122 = () => import(/* webpackChunkName: "page-pages-parametrage-permissions" */ "@/pages/parametrage/Permissions");
registerRoutePrefetch("/parametrage/permissions", import_Page_122);
const Page_122 = lazy(import_Page_122);
const import_Page_123 = () => import(/* webpackChunkName: "page-pages-parametrage-permissionsadmin" */ "@/pages/parametrage/PermissionsAdmin");
registerRoutePrefetch("/parametrage/permissionsadmin", import_Page_123);
const Page_123 = lazy(import_Page_123);
const import_Page_124 = () => import(/* webpackChunkName: "page-pages-parametrage-permissionsform" */ "@/pages/parametrage/PermissionsForm");
registerRoutePrefetch("/parametrage/permissionsform", import_Page_124);
const Page_124 = lazy(import_Page_124);
const import_Page_125 = () => import(/* webpackChunkName: "page-pages-parametrage-rgpdconsentform" */ "@/pages/parametrage/RGPDConsentForm");
registerRoutePrefetch("/parametrage/rgpdconsentform", import_Page_125);
const Page_125 = lazy(import_Page_125);
const import_Page_126 = () => import(/* webpackChunkName: "page-pages-parametrage-roleform" */ "@/pages/parametrage/RoleForm");
registerRoutePrefetch("/parametrage/roleform", import_Page_126);
const Page_126 = lazy(import_Page_126);
const import_Page_127 = () => import(/* webpackChunkName: "page-pages-parametrage-roles" */ "@/pages/parametrage/Roles");
registerRoutePrefetch("/parametrage/roles", import_Page_127);
const Page_127 = lazy(import_Page_127);
const import_Page_128 = () => import(/* webpackChunkName: "page-pages-parametrage-sousfamilles" */ "@/pages/Parametrage/SousFamilles");
registerRoutePrefetch("/parametrage/sousfamilles", import_Page_128);
const Page_128 = lazy(import_Page_128);
const import_Page_129 = () => import(/* webpackChunkName: "page-pages-parametrage-sousfamilles" */ "@/pages/parametrage/SousFamilles");
registerRoutePrefetch("/parametrage/sousfamilles", import_Page_129);
const Page_129 = lazy(import_Page_129);
const import_Page_130 = () => import(/* webpackChunkName: "page-pages-parametrage-systemtools" */ "@/pages/parametrage/SystemTools");
registerRoutePrefetch("/parametrage/systemtools", import_Page_130);
const Page_130 = lazy(import_Page_130);
const import_Page_131 = () => import(/* webpackChunkName: "page-pages-parametrage-templatecommandeform" */ "@/pages/parametrage/TemplateCommandeForm");
registerRoutePrefetch("/parametrage/templatecommandeform", import_Page_131);
const Page_131 = lazy(import_Page_131);
const import_Page_132 = () => import(/* webpackChunkName: "page-pages-parametrage-templatescommandes" */ "@/pages/parametrage/TemplatesCommandes");
registerRoutePrefetch("/parametrage/templatescommandes", import_Page_132);
const Page_132 = lazy(import_Page_132);
const import_Page_133 = () => import(/* webpackChunkName: "page-pages-parametrage-unites" */ "@/pages/Parametrage/Unites");
registerRoutePrefetch("/parametrage/unites", import_Page_133);
const Page_133 = lazy(import_Page_133);
const import_Page_134 = () => import(/* webpackChunkName: "page-pages-parametrage-unites" */ "@/pages/parametrage/Unites");
registerRoutePrefetch("/parametrage/unites", import_Page_134);
const Page_134 = lazy(import_Page_134);
const import_Page_135 = () => import(/* webpackChunkName: "page-pages-parametrage-utilisateurs" */ "@/pages/parametrage/Utilisateurs");
registerRoutePrefetch("/parametrage/utilisateurs", import_Page_135);
const Page_135 = lazy(import_Page_135);
const import_Page_136 = () => import(/* webpackChunkName: "page-pages-parametrage-zoneaccess" */ "@/pages/parametrage/ZoneAccess");
registerRoutePrefetch("/parametrage/zoneaccess", import_Page_136);
const Page_136 = lazy(import_Page_136);
const import_Page_137 = () => import(/* webpackChunkName: "page-pages-parametrage-zoneform" */ "@/pages/parametrage/ZoneForm");
registerRoutePrefetch("/parametrage/zoneform", import_Page_137);
const Page_137 = lazy(import_Page_137);
const import_Page_138 = () => import(/* webpackChunkName: "page-pages-parametrage-zones" */ "@/pages/parametrage/Zones");
registerRoutePrefetch("/parametrage/zones", import_Page_138);
const Page_138 = lazy(import_Page_138);
const import_Page_139 = () => import(/* webpackChunkName: "page-pages-parametres-familles" */ "@/pages/Parametres/Familles");
registerRoutePrefetch("/parametres/familles", import_Page_139);
const Page_139 = lazy(import_Page_139);
const import_Page_140 = () => import(/* webpackChunkName: "page-pages-pertes" */ "@/pages/Pertes");
registerRoutePrefetch("/pertes", import_Page_140);
const Page_140 = lazy(import_Page_140);
const import_Page_141 = () => import(/* webpackChunkName: "page-pages-planning" */ "@/pages/Planning");
registerRoutePrefetch("/planning", import_Page_141);
const Page_141 = lazy(import_Page_141);
const import_Page_142 = () => import(/* webpackChunkName: "page-pages-planning-simulationplanner" */ "@/pages/planning/SimulationPlanner");
registerRoutePrefetch("/planning/simulationplanner", import_Page_142);
const Page_142 = lazy(import_Page_142);
const import_Page_143 = () => import(/* webpackChunkName: "page-pages-planningdetail" */ "@/pages/PlanningDetail");
registerRoutePrefetch("/planningdetail", import_Page_143);
const Page_143 = lazy(import_Page_143);
const import_Page_144 = () => import(/* webpackChunkName: "page-pages-planningform" */ "@/pages/PlanningForm");
registerRoutePrefetch("/planningform", import_Page_144);
const Page_144 = lazy(import_Page_144);
const import_Page_145 = () => import(/* webpackChunkName: "page-pages-planningmodule" */ "@/pages/PlanningModule");
registerRoutePrefetch("/planningmodule", import_Page_145);
const Page_145 = lazy(import_Page_145);
const import_Page_146 = () => import(/* webpackChunkName: "page-pages-produits-produitdetail" */ "@/pages/produits/ProduitDetail");
registerRoutePrefetch("/produits/produitdetail", import_Page_146);
const Page_146 = lazy(import_Page_146);
const import_Page_147 = () => import(/* webpackChunkName: "page-pages-produits-produitform" */ "@/pages/produits/ProduitForm");
registerRoutePrefetch("/produits/produitform", import_Page_147);
const Page_147 = lazy(import_Page_147);
const import_Page_148 = () => import(/* webpackChunkName: "page-pages-produits-produits" */ "@/pages/produits/Produits");
registerRoutePrefetch("/produits/produits", import_Page_148);
const Page_148 = lazy(import_Page_148);
const import_Page_149 = () => import(/* webpackChunkName: "page-pages-promotions-promotionform" */ "@/pages/promotions/PromotionForm");
registerRoutePrefetch("/promotions/promotionform", import_Page_149);
const Page_149 = lazy(import_Page_149);
const import_Page_150 = () => import(/* webpackChunkName: "page-pages-promotions-promotions" */ "@/pages/promotions/Promotions");
registerRoutePrefetch("/promotions/promotions", import_Page_150);
const Page_150 = lazy(import_Page_150);
const import_Page_151 = () => import(/* webpackChunkName: "page-pages-public-landingpage" */ "@/pages/public/LandingPage");
registerRoutePrefetch("/public/landingpage", import_Page_151);
const Page_151 = lazy(import_Page_151);
const import_Page_152 = () => import(/* webpackChunkName: "page-pages-public-signup" */ "@/pages/public/Signup");
registerRoutePrefetch("/public/signup", import_Page_152);
const Page_152 = lazy(import_Page_152);
const import_Page_153 = () => import(/* webpackChunkName: "page-pages-receptions-receptions" */ "@/pages/receptions/Receptions");
registerRoutePrefetch("/receptions/receptions", import_Page_153);
const Page_153 = lazy(import_Page_153);
const import_Page_154 = () => import(/* webpackChunkName: "page-pages-recettes-recettes" */ "@/pages/recettes/Recettes");
registerRoutePrefetch("/recettes/recettes", import_Page_154);
const Page_154 = lazy(import_Page_154);
const import_Page_155 = () => import(/* webpackChunkName: "page-pages-reporting-graphcost" */ "@/pages/reporting/GraphCost");
registerRoutePrefetch("/reporting/graphcost", import_Page_155);
const Page_155 = lazy(import_Page_155);
const import_Page_156 = () => import(/* webpackChunkName: "page-pages-reporting-reporting" */ "@/pages/reporting/Reporting");
registerRoutePrefetch("/reporting/reporting", import_Page_156);
const Page_156 = lazy(import_Page_156);
const import_Page_157 = () => import(/* webpackChunkName: "page-pages-reporting-reportingpdf" */ "@/pages/reporting/ReportingPDF");
registerRoutePrefetch("/reporting/reportingpdf", import_Page_157);
const Page_157 = lazy(import_Page_157);
const import_Page_158 = () => import(/* webpackChunkName: "page-pages-requisitions-requisitiondetail" */ "@/pages/requisitions/RequisitionDetail");
registerRoutePrefetch("/requisitions/requisitiondetail", import_Page_158);
const Page_158 = lazy(import_Page_158);
const import_Page_159 = () => import(/* webpackChunkName: "page-pages-requisitions-requisitionform" */ "@/pages/requisitions/RequisitionForm");
registerRoutePrefetch("/requisitions/requisitionform", import_Page_159);
const Page_159 = lazy(import_Page_159);
const import_Page_160 = () => import(/* webpackChunkName: "page-pages-requisitions-requisitions" */ "@/pages/requisitions/Requisitions");
registerRoutePrefetch("/requisitions/requisitions", import_Page_160);
const Page_160 = lazy(import_Page_160);
const import_Page_161 = () => import(/* webpackChunkName: "page-pages-rgpd" */ "@/pages/Rgpd");
registerRoutePrefetch("/rgpd", import_Page_161);
const Page_161 = lazy(import_Page_161);
const import_Page_162 = () => import(/* webpackChunkName: "page-pages-settings" */ "@/pages/Settings");
registerRoutePrefetch("/settings", import_Page_162);
const Page_162 = lazy(import_Page_162);
const import_Page_163 = () => import(/* webpackChunkName: "page-pages-setup-firstrun" */ "@/pages/setup/FirstRun");
registerRoutePrefetch("/setup/firstrun", import_Page_163);
const Page_163 = lazy(import_Page_163);
const import_Page_164 = () => import(/* webpackChunkName: "page-pages-signalements-signalementdetail" */ "@/pages/signalements/SignalementDetail");
registerRoutePrefetch("/signalements/signalementdetail", import_Page_164);
const Page_164 = lazy(import_Page_164);
const import_Page_165 = () => import(/* webpackChunkName: "page-pages-signalements-signalementform" */ "@/pages/signalements/SignalementForm");
registerRoutePrefetch("/signalements/signalementform", import_Page_165);
const Page_165 = lazy(import_Page_165);
const import_Page_166 = () => import(/* webpackChunkName: "page-pages-signalements-signalements" */ "@/pages/signalements/Signalements");
registerRoutePrefetch("/signalements/signalements", import_Page_166);
const Page_166 = lazy(import_Page_166);
const import_Page_167 = () => import(/* webpackChunkName: "page-pages-simulation-simulation" */ "@/pages/simulation/Simulation");
registerRoutePrefetch("/simulation/simulation", import_Page_167);
const Page_167 = lazy(import_Page_167);
const import_Page_168 = () => import(/* webpackChunkName: "page-pages-simulation-simulationform" */ "@/pages/simulation/SimulationForm");
registerRoutePrefetch("/simulation/simulationform", import_Page_168);
const Page_168 = lazy(import_Page_168);
const import_Page_169 = () => import(/* webpackChunkName: "page-pages-simulation-simulationmenu" */ "@/pages/simulation/SimulationMenu");
registerRoutePrefetch("/simulation/simulationmenu", import_Page_169);
const Page_169 = lazy(import_Page_169);
const import_Page_170 = () => import(/* webpackChunkName: "page-pages-simulation-simulationresult" */ "@/pages/simulation/SimulationResult");
registerRoutePrefetch("/simulation/simulationresult", import_Page_170);
const Page_170 = lazy(import_Page_170);
const import_Page_171 = () => import(/* webpackChunkName: "page-pages-stats-stats" */ "@/pages/stats/Stats");
registerRoutePrefetch("/stats/stats", import_Page_171);
const Page_171 = lazy(import_Page_171);
const import_Page_172 = () => import(/* webpackChunkName: "page-pages-stats-statsadvanced" */ "@/pages/stats/StatsAdvanced");
registerRoutePrefetch("/stats/statsadvanced", import_Page_172);
const Page_172 = lazy(import_Page_172);
const import_Page_173 = () => import(/* webpackChunkName: "page-pages-stats-statsconsolidation" */ "@/pages/stats/StatsConsolidation");
registerRoutePrefetch("/stats/statsconsolidation", import_Page_173);
const Page_173 = lazy(import_Page_173);
const import_Page_174 = () => import(/* webpackChunkName: "page-pages-stats-statscostcenters" */ "@/pages/stats/StatsCostCenters");
registerRoutePrefetch("/stats/statscostcenters", import_Page_174);
const Page_174 = lazy(import_Page_174);
const import_Page_175 = () => import(/* webpackChunkName: "page-pages-stats-statscostcenterspivot" */ "@/pages/stats/StatsCostCentersPivot");
registerRoutePrefetch("/stats/statscostcenterspivot", import_Page_175);
const Page_175 = lazy(import_Page_175);
const import_Page_176 = () => import(/* webpackChunkName: "page-pages-stats-statsfiches" */ "@/pages/stats/StatsFiches");
registerRoutePrefetch("/stats/statsfiches", import_Page_176);
const Page_176 = lazy(import_Page_176);
const import_Page_177 = () => import(/* webpackChunkName: "page-pages-stats-statsstock" */ "@/pages/stats/StatsStock");
registerRoutePrefetch("/stats/statsstock", import_Page_177);
const Page_177 = lazy(import_Page_177);
const import_Page_178 = () => import(/* webpackChunkName: "page-pages-stock" */ "@/pages/Stock");
registerRoutePrefetch("/stock", import_Page_178);
const Page_178 = lazy(import_Page_178);
const import_Page_179 = () => import(/* webpackChunkName: "page-pages-stock-alertesrupture" */ "@/pages/stock/AlertesRupture");
registerRoutePrefetch("/stock/alertesrupture", import_Page_179);
const Page_179 = lazy(import_Page_179);
const import_Page_180 = () => import(/* webpackChunkName: "page-pages-stock-inventaire" */ "@/pages/stock/Inventaire");
registerRoutePrefetch("/stock/inventaire", import_Page_180);
const Page_180 = lazy(import_Page_180);
const import_Page_181 = () => import(/* webpackChunkName: "page-pages-stock-inventaireform" */ "@/pages/stock/InventaireForm");
registerRoutePrefetch("/stock/inventaireform", import_Page_181);
const Page_181 = lazy(import_Page_181);
const import_Page_182 = () => import(/* webpackChunkName: "page-pages-stock-requisitions" */ "@/pages/stock/Requisitions");
registerRoutePrefetch("/stock/requisitions", import_Page_182);
const Page_182 = lazy(import_Page_182);
const import_Page_183 = () => import(/* webpackChunkName: "page-pages-stock-transfertform" */ "@/pages/stock/TransfertForm");
registerRoutePrefetch("/stock/transfertform", import_Page_183);
const Page_183 = lazy(import_Page_183);
const import_Page_184 = () => import(/* webpackChunkName: "page-pages-stock-transferts" */ "@/pages/stock/Transferts");
registerRoutePrefetch("/stock/transferts", import_Page_184);
const Page_184 = lazy(import_Page_184);
const import_Page_185 = () => import(/* webpackChunkName: "page-pages-supervision-comparateurfiches" */ "@/pages/supervision/ComparateurFiches");
registerRoutePrefetch("/supervision/comparateurfiches", import_Page_185);
const Page_185 = lazy(import_Page_185);
const import_Page_186 = () => import(/* webpackChunkName: "page-pages-supervision-groupeparamform" */ "@/pages/supervision/GroupeParamForm");
registerRoutePrefetch("/supervision/groupeparamform", import_Page_186);
const Page_186 = lazy(import_Page_186);
const import_Page_187 = () => import(/* webpackChunkName: "page-pages-supervision-logs" */ "@/pages/supervision/Logs");
registerRoutePrefetch("/supervision/logs", import_Page_187);
const Page_187 = lazy(import_Page_187);
const import_Page_188 = () => import(/* webpackChunkName: "page-pages-supervision-rapports" */ "@/pages/supervision/Rapports");
registerRoutePrefetch("/supervision/rapports", import_Page_188);
const Page_188 = lazy(import_Page_188);
const import_Page_189 = () => import(/* webpackChunkName: "page-pages-supervision-supervisiongroupe" */ "@/pages/supervision/SupervisionGroupe");
registerRoutePrefetch("/supervision/supervisiongroupe", import_Page_189);
const Page_189 = lazy(import_Page_189);
const import_Page_190 = () => import(/* webpackChunkName: "page-pages-surcouts-surcouts" */ "@/pages/surcouts/Surcouts");
registerRoutePrefetch("/surcouts/surcouts", import_Page_190);
const Page_190 = lazy(import_Page_190);
const import_Page_191 = () => import(/* webpackChunkName: "page-pages-taches-alertes" */ "@/pages/taches/Alertes");
registerRoutePrefetch("/taches/alertes", import_Page_191);
const Page_191 = lazy(import_Page_191);
const import_Page_192 = () => import(/* webpackChunkName: "page-pages-taches-tachedetail" */ "@/pages/taches/TacheDetail");
registerRoutePrefetch("/taches/tachedetail", import_Page_192);
const Page_192 = lazy(import_Page_192);
const import_Page_193 = () => import(/* webpackChunkName: "page-pages-taches-tacheform" */ "@/pages/taches/TacheForm");
registerRoutePrefetch("/taches/tacheform", import_Page_193);
const Page_193 = lazy(import_Page_193);
const import_Page_194 = () => import(/* webpackChunkName: "page-pages-taches-tachenew" */ "@/pages/taches/TacheNew");
registerRoutePrefetch("/taches/tachenew", import_Page_194);
const Page_194 = lazy(import_Page_194);
const import_Page_195 = () => import(/* webpackChunkName: "page-pages-taches-taches" */ "@/pages/taches/Taches");
registerRoutePrefetch("/taches/taches", import_Page_195);
const Page_195 = lazy(import_Page_195);
const import_Page_196 = () => import(/* webpackChunkName: "page-pages-utilisateurs" */ "@/pages/Utilisateurs");
registerRoutePrefetch("/utilisateurs", import_Page_196);
const Page_196 = lazy(import_Page_196);
const import_Page_197 = () => import(/* webpackChunkName: "page-pages-validations" */ "@/pages/Validations");
registerRoutePrefetch("/validations", import_Page_197);
const Page_197 = lazy(import_Page_197);

export const routes = [
  { path: "/accueil", element: <Page_0 /> },
  { path: "/achats/achatdetail", element: <Page_1 /> },
  { path: "/achats/achatform", element: <Page_2 /> },
  { path: "/achats/achats", element: <Page_3 /> },
  { path: "/alertes", element: <Page_4 /> },
  { path: "/analyse/analyse", element: <Page_5 /> },
  { path: "/analyse/analysecostcenter", element: <Page_6 /> },
  { path: "/analyse/menuengineering", element: <Page_7 /> },
  { path: "/analyse/tableauxdebord", element: <Page_8 /> },
  { path: "/analytique/analytiquedashboard", element: <Page_9 /> },
  { path: "/auth/blocked", element: <Page_10 /> },
  { path: "/auth/createmama", element: <Page_11 /> },
  { path: "/auth/logout", element: <Page_12 /> },
  { path: "/auth/pending", element: <Page_13 /> },
  { path: "/auth/resetpassword", element: <Page_14 /> },
  { path: "/auth/roleerror", element: <Page_15 /> },
  { path: "/auth/unauthorized", element: <Page_16 /> },
  { path: "/auth/updatepassword", element: <Page_17 /> },
  { path: "/barmanager", element: <Page_18 /> },
  { path: "/bons_livraison/blcreate", element: <Page_19 /> },
  { path: "/bons_livraison/bldetail", element: <Page_20 /> },
  { path: "/bons_livraison/blform", element: <Page_21 /> },
  { path: "/bons_livraison/bonslivraison", element: <Page_22 /> },
  { path: "/carte/carte", element: <Page_23 /> },
  { path: "/carteplats", element: <Page_24 /> },
  { path: "/catalogue/cataloguesyncviewer", element: <Page_25 /> },
  { path: "/commandes/commandedetail", element: <Page_26 /> },
  { path: "/commandes/commandeform", element: <Page_27 /> },
  { path: "/commandes/commandes", element: <Page_28 /> },
  { path: "/commandes/commandesenvoyees", element: <Page_29 /> },
  { path: "/consentements", element: <Page_30 /> },
  { path: "/consolidation/accessmultisites", element: <Page_31 /> },
  { path: "/consolidation/consolidation", element: <Page_32 /> },
  { path: "/costboisson/costboisson", element: <Page_33 /> },
  { path: "/costing/costingcarte", element: <Page_34 /> },
  { path: "/cuisine/menudujour", element: <Page_35 /> },
  { path: "/dashboard", element: <Page_36 /> },
  { path: "/dashboard/dashboardbuilder", element: <Page_37 /> },
  { path: "/dbsetup", element: <Page_38 /> },
  { path: "/debug/accessexample", element: <Page_39 /> },
  { path: "/debug/auth", element: <Page_40 /> },
  { path: "/debug/auth", element: <Page_41 /> },
  { path: "/debug/authdebug", element: <Page_42 /> },
  { path: "/debug/debug", element: <Page_43 /> },
  { path: "/debug/debugauth", element: <Page_44 /> },
  { path: "/debug/debugrights", element: <Page_45 /> },
  { path: "/debug/debuguser", element: <Page_46 /> },
  { path: "/documents/documentform", element: <Page_47 /> },
  { path: "/documents/documents", element: <Page_48 /> },
  { path: "/dossierdonnees", element: <Page_49 /> },
  { path: "/ecarts/ecarts", element: <Page_50 /> },
  { path: "/emails/emailsenvoyes", element: <Page_51 /> },
  { path: "/engineering/menuengineering", element: <Page_52 /> },
  { path: "/engineeringmenu", element: <Page_53 /> },
  { path: "/factures/facturecreate", element: <Page_54 /> },
  { path: "/factures/facturedetail", element: <Page_55 /> },
  { path: "/factures/factureform", element: <Page_56 /> },
  { path: "/factures/factures", element: <Page_57 /> },
  { path: "/factures/importfactures", element: <Page_58 /> },
  { path: "/feedback", element: <Page_59 /> },
  { path: "/fiches/fichedetail", element: <Page_60 /> },
  { path: "/fiches/ficheform", element: <Page_61 /> },
  { path: "/fiches/fiches", element: <Page_62 /> },
  { path: "/fournisseurs/apifournisseurform", element: <Page_63 /> },
  { path: "/fournisseurs/apifournisseurs", element: <Page_64 /> },
  { path: "/fournisseurs/comparatif/comparatifprix", element: <Page_65 /> },
  { path: "/fournisseurs/comparatif/prixfournisseurs", element: <Page_66 /> },
  { path: "/fournisseurs/fournisseurapisettingsform", element: <Page_67 /> },
  { path: "/fournisseurs/fournisseurcreate", element: <Page_68 /> },
  { path: "/fournisseurs/fournisseurdetail", element: <Page_69 /> },
  { path: "/fournisseurs/fournisseurdetailpage", element: <Page_70 /> },
  { path: "/fournisseurs/fournisseurform", element: <Page_71 /> },
  { path: "/fournisseurs/fournisseurs", element: <Page_72 /> },
  { path: "/inventaire/ecartinventaire", element: <Page_73 /> },
  { path: "/inventaire/inventaire", element: <Page_74 /> },
  { path: "/inventaire/inventairedetail", element: <Page_75 /> },
  { path: "/inventaire/inventaireform", element: <Page_76 /> },
  { path: "/inventaire/inventairezones", element: <Page_77 /> },
  { path: "/journal", element: <Page_78 /> },
  { path: "/legal/cgu", element: <Page_79 /> },
  { path: "/legal/cgv", element: <Page_80 /> },
  { path: "/legal/confidentialite", element: <Page_81 /> },
  { path: "/legal/contact", element: <Page_82 /> },
  { path: "/legal/licence", element: <Page_83 /> },
  { path: "/legal/mentionslegales", element: <Page_84 /> },
  { path: "/login", element: <Page_85 /> },
  { path: "/menu/menudujour", element: <Page_86 /> },
  { path: "/menu/menudujourjour", element: <Page_87 /> },
  { path: "/menus/menudetail", element: <Page_88 /> },
  { path: "/menus/menudujour", element: <Page_89 /> },
  { path: "/menus/menudujourdetail", element: <Page_90 /> },
  { path: "/menus/menudujourform", element: <Page_91 /> },
  { path: "/menus/menuform", element: <Page_92 /> },
  { path: "/menus/menugroupedetail", element: <Page_93 /> },
  { path: "/menus/menugroupeform", element: <Page_94 /> },
  { path: "/menus/menugroupes", element: <Page_95 /> },
  { path: "/menus/menupdf", element: <Page_96 /> },
  { path: "/menus/menus", element: <Page_97 /> },
  { path: "/mobile/mobileaccueil", element: <Page_98 /> },
  { path: "/mobile/mobileinventaire", element: <Page_99 /> },
  { path: "/mobile/mobilerequisition", element: <Page_100 /> },
  { path: "/notfound", element: <Page_101 /> },
  { path: "/notifications/notificationsettingsform", element: <Page_102 /> },
  { path: "/notifications/notificationsinbox", element: <Page_103 /> },
  { path: "/parametrage/accessrights", element: <Page_104 /> },
  { path: "/parametrage/apikeys", element: <Page_105 /> },
  { path: "/parametrage/centrecoutform", element: <Page_106 /> },
  { path: "/parametrage/compteslocaux", element: <Page_107 /> },
  { path: "/parametrage/dossierdonnees", element: <Page_108 /> },
  { path: "/parametrage/dossierdonnees", element: <Page_109 /> },
  { path: "/parametrage/exportcomptapage", element: <Page_110 /> },
  { path: "/parametrage/exportuserdata", element: <Page_111 /> },
  { path: "/parametrage/familles", element: <Page_112 /> },
  { path: "/parametrage/familles", element: <Page_113 /> },
  { path: "/parametrage/invitationsenattente", element: <Page_114 /> },
  { path: "/parametrage/inviteuser", element: <Page_115 /> },
  { path: "/parametrage/mamaform", element: <Page_116 /> },
  { path: "/parametrage/mamas", element: <Page_117 /> },
  { path: "/parametrage/mamasettingsform", element: <Page_118 /> },
  { path: "/parametrage/parametrage", element: <Page_119 /> },
  { path: "/parametrage/parametrescommandes", element: <Page_120 /> },
  { path: "/parametrage/periodes", element: <Page_121 /> },
  { path: "/parametrage/permissions", element: <Page_122 /> },
  { path: "/parametrage/permissionsadmin", element: <Page_123 /> },
  { path: "/parametrage/permissionsform", element: <Page_124 /> },
  { path: "/parametrage/rgpdconsentform", element: <Page_125 /> },
  { path: "/parametrage/roleform", element: <Page_126 /> },
  { path: "/parametrage/roles", element: <Page_127 /> },
  { path: "/parametrage/sousfamilles", element: <Page_128 /> },
  { path: "/parametrage/sousfamilles", element: <Page_129 /> },
  { path: "/parametrage/systemtools", element: <Page_130 /> },
  { path: "/parametrage/templatecommandeform", element: <Page_131 /> },
  { path: "/parametrage/templatescommandes", element: <Page_132 /> },
  { path: "/parametrage/unites", element: <Page_133 /> },
  { path: "/parametrage/unites", element: <Page_134 /> },
  { path: "/parametrage/utilisateurs", element: <Page_135 /> },
  { path: "/parametrage/zoneaccess", element: <Page_136 /> },
  { path: "/parametrage/zoneform", element: <Page_137 /> },
  { path: "/parametrage/zones", element: <Page_138 /> },
  { path: "/parametres/familles", element: <Page_139 /> },
  { path: "/pertes", element: <Page_140 /> },
  { path: "/planning", element: <Page_141 /> },
  { path: "/planning/simulationplanner", element: <Page_142 /> },
  { path: "/planningdetail", element: <Page_143 /> },
  { path: "/planningform", element: <Page_144 /> },
  { path: "/planningmodule", element: <Page_145 /> },
  { path: "/produits/produitdetail", element: <Page_146 /> },
  { path: "/produits/produitform", element: <Page_147 /> },
  { path: "/produits/produits", element: <Page_148 /> },
  { path: "/promotions/promotionform", element: <Page_149 /> },
  { path: "/promotions/promotions", element: <Page_150 /> },
  { path: "/public/landingpage", element: <Page_151 /> },
  { path: "/public/signup", element: <Page_152 /> },
  { path: "/receptions/receptions", element: <Page_153 /> },
  { path: "/recettes/recettes", element: <Page_154 /> },
  { path: "/reporting/graphcost", element: <Page_155 /> },
  { path: "/reporting/reporting", element: <Page_156 /> },
  { path: "/reporting/reportingpdf", element: <Page_157 /> },
  { path: "/requisitions/requisitiondetail", element: <Page_158 /> },
  { path: "/requisitions/requisitionform", element: <Page_159 /> },
  { path: "/requisitions/requisitions", element: <Page_160 /> },
  { path: "/rgpd", element: <Page_161 /> },
  { path: "/settings", element: <Page_162 /> },
  { path: "/setup/firstrun", element: <Page_163 /> },
  { path: "/signalements/signalementdetail", element: <Page_164 /> },
  { path: "/signalements/signalementform", element: <Page_165 /> },
  { path: "/signalements/signalements", element: <Page_166 /> },
  { path: "/simulation/simulation", element: <Page_167 /> },
  { path: "/simulation/simulationform", element: <Page_168 /> },
  { path: "/simulation/simulationmenu", element: <Page_169 /> },
  { path: "/simulation/simulationresult", element: <Page_170 /> },
  { path: "/stats/stats", element: <Page_171 /> },
  { path: "/stats/statsadvanced", element: <Page_172 /> },
  { path: "/stats/statsconsolidation", element: <Page_173 /> },
  { path: "/stats/statscostcenters", element: <Page_174 /> },
  { path: "/stats/statscostcenterspivot", element: <Page_175 /> },
  { path: "/stats/statsfiches", element: <Page_176 /> },
  { path: "/stats/statsstock", element: <Page_177 /> },
  { path: "/stock", element: <Page_178 /> },
  { path: "/stock/alertesrupture", element: <Page_179 /> },
  { path: "/stock/inventaire", element: <Page_180 /> },
  { path: "/stock/inventaireform", element: <Page_181 /> },
  { path: "/stock/requisitions", element: <Page_182 /> },
  { path: "/stock/transfertform", element: <Page_183 /> },
  { path: "/stock/transferts", element: <Page_184 /> },
  { path: "/supervision/comparateurfiches", element: <Page_185 /> },
  { path: "/supervision/groupeparamform", element: <Page_186 /> },
  { path: "/supervision/logs", element: <Page_187 /> },
  { path: "/supervision/rapports", element: <Page_188 /> },
  { path: "/supervision/supervisiongroupe", element: <Page_189 /> },
  { path: "/surcouts/surcouts", element: <Page_190 /> },
  { path: "/taches/alertes", element: <Page_191 /> },
  { path: "/taches/tachedetail", element: <Page_192 /> },
  { path: "/taches/tacheform", element: <Page_193 /> },
  { path: "/taches/tachenew", element: <Page_194 /> },
  { path: "/taches/taches", element: <Page_195 /> },
  { path: "/utilisateurs", element: <Page_196 /> },
  { path: "/validations", element: <Page_197 /> }
];
