name: front-audit

on:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run front:audit
      - uses: actions/upload-artifact@v4
        with:
          name: front-audit
          path: |
            docs/FRONTMAP.md
            docs/front_map.json
