name: Verify local

on:
  pull_request:

jobs:
  verify:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Assert Windows
        run: |
          $isWin = $env:OS -eq "Windows_NT"
          if (-not $isWin) { Write-Error "Not Windows"; exit 1 }
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: npm ci
      - run: npm run build
      - run: npm run db:smoke
      - run: npm run check:tauri --if-present
      - run: npm run lint

